package src.ui.controls;

import java.awt.BorderLayout;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import javafx.application.Platform;
import javafx.embed.swing.JFXPanel;
import javafx.scene.Group;
import javafx.scene.Scene;
import javafx.scene.web.WebEngine;
import javafx.scene.web.WebView;

public class SwingWebView extends javax.swing.JPanel
{

    private WebEngine webEngine;
    private WebView webView;

    /**
     * Creates new form SwingWebView
     */
    public SwingWebView()
    {
        initComponents();
        init();
    }

    public void open(final String url)
    {
        Platform.runLater(new Runnable()
        {
            @Override
            public void run()
            {
                webEngine.load(url);
                return;
            }
        });
    }

    public void openContent(final String content)
    {
        Platform.runLater(new Runnable()
        {
            @Override
            public void run()
            {
                webEngine.loadContent(content);
                return;
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void init()
    {
        // This method is invoked on Swing thread
        final JFXPanel fxPanel = new JFXPanel();
        this.setLayout(new BorderLayout());
        this.add(fxPanel);

        this.addComponentListener(new ComponentAdapter()
        {
            @Override
            public void componentResized(ComponentEvent e)
            {
                final double w = SwingWebView.this.getSize().width;
                final double h = SwingWebView.this.getSize().height;

                Platform.runLater(new Runnable()
                {
                    @Override
                    public void run()
                    {
                        webView.setPrefSize(w, h);
                    }
                });
            }
        });

        Platform.runLater(new Runnable()
        {
            @Override
            public void run()
            {
                initFX(fxPanel);
            }
        });
    }

    private void initFX(JFXPanel fxPanel)
    {
        Group group = new Group();
        Scene scene = new Scene(group);
        fxPanel.setScene(scene);

        webView = new WebView();
        webView.setFontScale(0.82);

        group.getChildren().add(webView);

        // Obtain the webEngine to navigate
        webEngine = webView.getEngine();

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
